root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app.exe ./cmd/api"
bin = "tmp/app.exe"
delay = 1000
exclude_dir = ["tmp", "vendor", "tests", ".git"]
include_ext = ["go"]

[log]
time = true